In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 48.5 MB/s eta 0:00:0000:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 38.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 KB 18.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
#pandas와 numpy를 import 시킴
import numpy as np
import pandas as pd

## test yourself

* $ a = [1, 2, 3], b = [4, 5, 6] $일 때 배운 np 연산을 이용하여 32를 출력해보시오.
* 행렬연산을 이용해보시오.

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [21]:
np.sum(a[1])

2

In [3]:
(a[1]+b[2])*b[0]

32

In [4]:
np.sum(a)

6

* 산술연산을 이용해보시오.

In [5]:
np.sum(b)

15

$$\begin{pmatrix} 5 & 2 & 5 \\ 1 & 7 & 4 \\ -4 & 8 & 5 \end{pmatrix}$$
* 주어진 (1) 행렬의 값을 5배 키워보시오.

In [23]:
a = np.array([[5,2,5], 
     [1,7,4],
    [-4,8,5]
    ])

In [24]:
print(a)

[[ 5  2  5]
 [ 1  7  4]
 [-4  8  5]]


In [27]:
a*5

array([[ 25,  10,  25],
       [  5,  35,  20],
       [-20,  40,  25]])

In [28]:
print(np.multiply(5,a))

[[ 25  10  25]
 [  5  35  20]
 [-20  40  25]]


In [29]:
a

array([[ 5,  2,  5],
       [ 1,  7,  4],
       [-4,  8,  5]])

* 주어진 (1) 3x3 행렬에서 axis 1와 axis 2으로 sum을 한 각각의 결과를 서로 product하여 scalar값을 출력해보시오.

In [45]:
one = np.sum(a, axis=0)

In [46]:
two = np.sum(a, axis=1)

In [49]:
two

array([12, 12,  9])

In [48]:
np.sum(one)*np.sum(two)

1089

## test yourself

In [3]:
df = pd.read_csv('titanic.csv')
df.head(10)

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   
5         0       3                                    Mr. James Moran   
6         0       1                             Mr. Timothy J McCarthy   
7         0       3                      Master. Gosta Leonard Palsson   
8         1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson   
9         1       2                 Mrs. Nicholas (Adele Achem) Nasser   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500  
5    male  27.0                        0                        0   8.4583  
6    male  54.0                        0                        0  51.8625  
7    male   2.0                        3                        1  21.0750  
8  female  27.0                        0                        2  11.1333  
9  female  14.0                        1                        0  30.0708

* 주어진 타이타닉 사고 데이터를 이용하여 남성/여성의 총 인원수를 집계해보시오

In [ ]:
grouped = df.groupby('Sex')

In [61]:
grouped['Survived'].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

* 주어진 타이타닉 데이터에서 생존 남성의 평균 연령, 생존 여성의 평균 연령을 산출해보시오.

In [59]:
grouped.mean()

Survived    Pclass        Age  Siblings/Spouses Aboard  \
Sex                                                              
female  0.742038  2.159236  27.719745                 0.694268   
male    0.190227  2.385689  30.431361                 0.432810   

        Parents/Children Aboard       Fare  
Sex                                         
female                 0.649682  44.479818  
male                   0.237347  25.633935

* 타이타닉 사고 데이터에서 남성의 생존률과 여성의 생존률을 Pclass 대비로 측정해 보시오

In [54]:
P = df.groupby('Pclass')

In [60]:
df.groupby('Pclass').count()

Survived  Name  Sex  Age  Siblings/Spouses Aboard  \
Pclass                                                      
1            216   216  216  216                      216   
2            184   184  184  184                      184   
3            487   487  487  487                      487   

        Parents/Children Aboard  Fare  
Pclass                                 
1                           216   216  
2                           184   184  
3                           487   487

In [57]:
P['Survived'].sum() 

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64